server:
  port: 8080

spring:
  profiles:
    active: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG


agenda-cesep:
  password:
    client: ${CLIENT_PASS:teste}

springdoc:
  swagger-ui:
    oauth:
      clientId: newClient
      clientSecret: newClientSecret
  oAuthFlow:
    tokenUrl: ${OAUTH2_SERVER:http://localhost:8080}/oauth/token




    #management:
    #  endpoints:
    #    web:
    #      exposure:
    #        include: prometheus
    #  endpoint:
    #    prometheus:
    #      enabled: true
    #
    #aws:
    #  cloudwatch:
    #    enabled: true
    #    region: us-west-2
    #    namespace: gestao_agenda_backend
    #  metrics:
    #    enabled: false