server:
  port: 8080


spring:
  config:
    activate:
      on-profile: dev

  # Configurações do banco de dados MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/cesep?createDatabaseIfNotExist=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: cesep
    password: 124578*-
#  sql.init.mode: never

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true



agenda-cesep:
  password:
    client: ${CLIENT_PASS:teste}

springdoc:
  swagger-ui:
    oauth:
      clientId: cesep-agenda-frontend
      clientSecret: teste

  oAuthFlow:
    tokenUrl: ${OAUTH2_SERVER:http://localhost:8080}/oauth/token